name: Publish on Modrinth
on:
  push:
    tags:
      - '*'
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Fetch Tags
        run: git fetch --unshallow --tags -f
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Publish Jar to Modrinth
        env:
          MODRINTH_TOKEN: ${{secrets.MODRINTH_TOKEN}}
        run: ./gradlew modrinth
      - name: Publish Jar to CurseForge
        env:
          CURSEFORGE_API_KEY: ${{secrets.CURSEFORGE_API_KEY}}
        run: ./gradlew curseforge
